name: Build and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./docs # Adjust if your package.json is elsewhere
        run: bun install

      # Step 4: Build the site
      - name: Build the site
        working-directory: ./docs # Adjust if your build script is elsewhere
        run: bun run build

      # Step 5: Copy build output to docs folder
      - name: Copy build output to docs
        run: |
          mkdir -p docs # Ensure the docs folder exists
          cp -r ./docs/dist/* ./docs/ # Adjust 'dist' if your build output folder is different
      # Step 6: Commit changes to docs folder
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update docs with new build output" || echo "No changes to commit"
          git push
