name: Build and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      # Step 3: Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: ./docs
        run: bun install

      # Step 5: Build the site
      - name: Build the site
        working-directory: ./docs
        run: bun run build

      # Step 6: Debug the build output
      - name: List build output
        run: ls -R ./docs/.next # List files in the .next folder

      # Step 7: Copy build output to docs folder
      - name: Copy build output to docs
        run: |
          mkdir -p docs
          cp -r ./docs/.next/* ./docs/
      
      # Step 8: Commit changes to docs folder
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update docs with new build output" || echo "No changes to commit"
          git push
